name: GitHub Action with Email Address

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: ${{ secrets.MY_EMAIL }}
        run: echo "Hello, world!"
