name: GitHub Action with Email Address

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: "21f1001681@ds.study.iitm.ac.in"
        run: echo "Hello, world!"
